version: 2.1

executors:
docker-executor:
  docker:
    - image: google/cloud-sdk:latest
  working_directory: ~/repo
jobs:
  checkout_code:
    executor: docker-executor
    steps:
      - checkout
  build_docker_image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker
      - run:
          name: Build and Push image
          command : |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops9/mlops_image:latest .
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops9/mlops_image:latest
  deploy_to_gke:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker
      - run:
          name: configure GKE
          command: |
            gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --prject $GOOGLE_PROJECT_ID
      - run:
          name: Deploy to GKE
          command: |
            kubectl apply -f kubernetes-deployment.yaml
            kubectl set image deployment/mlops9 mlops9=us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops9/mlops_image:latest
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image